main:
- name: Blog
  url: /posts/
  weight: 1

- name: Teaching
  url: /teaching/
  weight: 2

social:
- name: email
  url: mailto:email@example.com
  weight: 1
  params:
    icon: fas fa-envelope

- name: LinkedIn
  url: https://www.linkedin.com/username
  weight: 2
  params:
    icon: fab fa-linkedin

- name: GitHub
  url: https://github.com/username
  weight: 3
  params:
    icon: fab fa-github

- name: RSS Feed
  url: /index.xml
  weight: 4
  params:
    icon: fas fa-square-rss
