firstName: Albert
lastName: Einstein

email: einstein@example.org

description: Albert Einstein's personal website powered by the Academic Folio theme

tags: # these tags would be added as keywords in metadata for website
- academic-folio
- academic-website
- al-folio
- hugo
- hugo-theme

maxWidth: 1024px

navbarTitle: true # displays the title in the navbar on non home pages

footerLastUpdated: true

recentPosts: 5 # number of recent posts to show in home page
showRecentPosts: true

recentNews: 5 # number of recent news to show in home page
showRecentNews: true

socialNavbar: true # show social icons on navbar
socialHomePage: true # show social icons on the home page

colorTheme: blue # choose a theme from `data/themes` folder
