baseURL: https://academic-folio.netlify.app
languageCode: en
title: Academic Folio
copyright: Â© Copyright 2023 The Academic Folio Contributors

# theme: academic-folio

enableEmoji: true

enableRobotsTXT: true

markup:
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/rohandebsarkar/academic-folio
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
